# Generated by Django 5.0.6 on 2024-06-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=10)),
                ('Projects', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Company', models.CharField(max_length=50)),
                ('Job_title', models.CharField(max_length=100)),
                ('Skills_required', models.TextField()),
                ('Job_type', models.CharField(max_length=30)),
            ],
        ),
    ]
