# Generated by Django 5.0.6 on 2024-06-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_application_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.IntegerField(),
        ),
    ]
